/**
 * Trace Lifter - Main Entry Point
 * 
 * This module lifts execution traces from the VM into readable JavaScript:
 * 1. Load execution traces (vm_call_stack.json)
 * 2. Convert to Intermediate Representation (IR)
 * 3. Lift IR to JavaScript AST
 * 4. Clean and beautify the output
 */

import fs from 'fs'
import { IntermediateRepresentationLifter } from './ir'
import { JavascriptLifter } from './lifter'
import { FunctionTrace } from './types'


import { parse } from "@babel/parser";
import { JavascriptBeautifier } from './cleaner';
import generate from '@babel/generator';

// Load execution traces from JSON file
// This file is generated by the deobfuscator's tracer
var functionTraces: {[key: string]: FunctionTrace[]}  = JSON.parse(fs.readFileSync('input/vm_call_stack.json').toString())

// Convert to Map structure for efficient lookup
const functionTraceMap = new Map<string, FunctionTrace[]>()

Object.keys(functionTraces).forEach((key)=> {
    const traces = functionTraces[key]
    functionTraceMap.set(key, traces)

})

// Step 1: Lift execution traces to Intermediate Representation
// This creates a structured representation of the control flow and operations
var irLifter = new IntermediateRepresentationLifter(functionTraceMap)

var ir = irLifter.lift()

// Step 2: Lift IR to JavaScript AST
// This converts the IR into actual JavaScript code structure
var jsLifter = new JavascriptLifter(ir)
var outputAst = jsLifter.lift()

// Step 3: Clean and beautify the output
// This makes the generated code more readable
var cleaner = new JavascriptBeautifier(outputAst)

// Write the final cleaned JavaScript to file
fs.writeFileSync("cleaned.js", cleaner.clean());
